### ISSUE TITLE
Implement Smooth Color Transition for Navbar on Scroll

### ISSUE THREAD

**Issue by GSO0** [PocariChie/BookingTour#9]
Hello @PocariChie

Having a first look at your site, I have to say that it’s a very nice project and developer-friendly. However, I noticed a few details.

1) The current navbar stays black as the user scrolls down, regardless of the section's background color. To improve the user experience and make the design smoother, I'd like the navbar color to transition smoothly to match the color of each new section it scrolls over. This will help the navbar blend better with the content and add a dynamic touch to the site.

2) Secondly i'd suggest to change the design of the navbar(e.g. the font).

For sure I would like to help you improve those details on the main page. Can you i work on this ?
Thank you

**Comment by PocariChie** [comment]
> Hello @PocariChie
> 
> Having a first look at your site, I have to say that it’s a very nice project and developer-friendly. However, I noticed a few details.
> 
> 1. The current navbar stays black as the user scrolls down, regardless of the section's background color. To improve the user experience and make the design smoother, I'd like the navbar color to transition smoothly to match the color of each new section it scrolls over. This will help the navbar blend better with the content and add a dynamic touch to the site.
> 2. Secondly i'd suggest to change the design of the navbar(e.g. the font).
> 
> For sure I would like to help you improve those details on the main page. Can you i work on this ? Thank you

Thank you !
